<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BsxtBatch.Core\BsxtBatch.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>backscatter-fish.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="backscatter-fish.ico" />
  </ItemGroup>

</Project>
